<div style="overflow:hidden;padding:10px;">
    <h3>About BackendManager</h3>
    <p>
        BackendManager is created by Boy van Moorsel alias <b>WitteStier</b><br />
        and is a open-source project available on <a href="https://github.com/WitteStier/BackendManager" target="_blank">github</a>.<br />
        Please help improving BackendManager by reporting bugs or to help developing.
    </p>
    <b>Versions:</b>
    <table style="border-top:1px solid #FF00FF;border-bottom:1px solid #FF00FF;margin-bottom:1.12em;">
        <tr>
            <td>ExtJs</td>
            <td>4.0.1</td>
            <td>Major, Minor, Patch</td>
        </tr>
        <tr>
            <td>ExtCore</td>
            <td>4.0.1</td>
            <td>Major, Minor, Patch</td>
        </tr>
        <tr>
            <td>BackendManager</td>
            <td>0.0.1</td>
            <td>Major, Minor, Build</td>
        </tr>
        <tr>
            <td>BackendManager Core</td>
            <td>0.0.1</td>
            <td>Major, Minor, Build</td>
        </tr>
    </table>
    <b>Contact & Information:</b>
    <ul style="margin:0 0 0 15px;">
        <li>
            View this open-source project on <a href="https://github.com/WitteStier/BackendManager" target="_blank">github</a>
        </li>
        <li>
            Do you want to help developing or testing <a href="mailto://development@wittestier.nl">development@wittestier.nl</a>
        </li>
        <li>
            Do you want a professional back-end application based on BackendManager <a href="mailto://development@wittestier.nl">jobs@wittestier.nl</a>
        </li>
    </ul>
</div>