<?php

$requestedWith = isset($_SERVER['HTTP_X_REQUESTED_WITH'])
    ? $_SERVER['HTTP_X_REQUESTED_WITH']
    : false;

if ($requestedWith && ('XMLHttpRequest' === $requestedWith)):
    // Very bad but working work-around.
    $this->layout()->setTemplate('error/404');

    header('Content-type: application/json');

    print json_encode(array(
        'success' => false,
        'message' => "You try to load data from a unknown, not found source."
    ));
else:
    ?>
    <script type="text/javascript">
        var loader = document.getElementById('application-header-loader');
        loader.style.visibility = 'hidden';

        alert('You try to open a unknown, not found page.\n Click OK to relaunch the system.');
        document.location = '/';
    </script>
<?php endif; ?>