<?php
$requestedWith = isset($_SERVER['HTTP_X_REQUESTED_WITH'])
    ? $_SERVER['HTTP_X_REQUESTED_WITH']
    : false;

if ($requestedWith && ('XMLHttpRequest' === $requestedWith)):
    // Very bad but working work-around.
    $this->layout()->setTemplate('error/index');

    header('Content-type: application/json');

    $response = array(
        'success' => false,
        'message' => "An error occurred."
    );

    if (isset($this->display_exceptions) && $this->display_exceptions) {
        if (!$this->exception || !$this->exception instanceof \Exception) {
            $response['exception'] = 'No Exception available';
        } else {
            $response['exception'] = array(
                'message' => $this->exception->getMessage(),
                'file' => sprintf(
                    '%s:%s', $this->exception->getFile(), $this->exception->getLine()
                ),
                'exception' => get_class($this->exception),
                'trace' => $this->exception->getTraceAsString(),
                'previous' => array(),
            );

            $previous = $this->exception->getPrevious();
            if ($previous) {
                $response['exception']['previous'] = array(
                    'message' => $previous->getMessage(),
                    'file' => sprintf(
                        '%s:%s', $previous->getFile(), $previous->getLine()
                    ),
                    'exception' => get_class($previous),
                    'trace' => $previous->getTraceAsString(),
                );
            }
        }
    }

    print json_encode($response);
    die; // Ugly work-around.
else:
    ?>
    TODO print data in view/error/index
    <script type="text/javascript">
        var loader = document.getElementById('application-header-loader');
        loader.style.visibility = 'hidden';
    </script>
<?php endif; ?>