<?php

$this->headLink()->appendStylesheet(
    'http://cdn.sencha.io/ext-4.2.0-gpl/resources/css/ext-all.css'
);

// Add javasctipt files
if ('production' == APPLICATION_ENV) {
    $this->headScript()
        ->appendFile('http://cdn.sencha.io/ext-4.2.0-gpl/ext.js')
        ->appendFile('js/application.js');
} else {
    $this->headScript()
        ->appendFile('http://cdn.sencha.io/ext-4.2.0-gpl/ext-debug.js')
        ->appendFile('js/application-dev.js')
        ->appendFile('js/application/i18n/nl_NL.js');
}